// apps/frontend-nuxt/src/pages/orders/[id].vue
<template>
  <div class="container py-8">
    <div v-if="loading" class="max-w-4xl mx-auto space-y-8">
      <div class="h-32 animate-pulse rounded-xl bg-muted" />
      <div class="grid md:grid-cols-3 gap-8">
        <div class="md:col-span-2 space-y-4">
          <div v-for="i in 3" :key="`skeleton-${i}`" class="h-40 animate-pulse rounded-xl bg-muted" />
        </div>
        <div class="space-y-4">
          <div class="h-60 animate-pulse rounded-xl bg-muted" />
        </div>
      </div>
    </div>

    <div v-else-if="order" class="max-w-4xl mx-auto">
      <Button variant="ghost" class="mb-6" @click="navigateTo('/orders')">
        ← Back to Orders
      </Button>

      <Card class="mb-8">
        <CardContent class="p-6">
          <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <h1 class="text-2xl font-bold mb-1">Order #{{ order.id }}</h1>
              <p class="text-muted-foreground">Placed on {{ new Date(order.created_at).toLocaleDateString() }}</p>
            </div>
            <Badge :variant="getStatusVariant(order.status)" class="text-sm px-4 py-2">
              {{ formatStatus(order.status) }}
            </Badge>
          </div>
        </CardContent>
      </Card>

      <div class="grid md:grid-cols-3 gap-8">
        <div class="md:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Order Items</CardTitle>
            </CardHeader>
            <CardContent>
              <div class="space-y-4">
                <div v-for="item in order.items" :key="item.id" class="flex gap-4 py-4 border-b last:border-0">
                  <img
                    :src="item.book_cover_image || 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=100&h=150&fit=crop'"
                    :alt="item.book_title || ''"
                    class="w-20 h-28 object-cover rounded-lg"
                  />
                  <div class="flex-1">
                    <p class="font-semibold">{{ item.book_title }}</p>
                    <p class="text-sm text-muted-foreground">{{ item.book_author }}</p>
                    <p class="text-sm text-muted-foreground mt-1">Qty: {{ item.quantity }}</p>
                  </div>
                  <div class="text-right">
                    <p class="font-bold">${{ (Number(item.price_at_purchase) * item.quantity).toFixed(2) }}</p>
                    <p class="text-sm text-muted-foreground">${{ item.price_at_purchase }} each</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card v-if="order.status_history && order.status_history.length > 0">
            <CardHeader>
              <CardTitle>Order Status History</CardTitle>
            </CardHeader>
            <CardContent>
              <div class="space-y-4">
                <div
                  v-for="(history, index) in order.status_history"
                  :key="history.id"
                  class="flex gap-4"
                >
                  <div class="flex flex-col items-center">
                    <div
                      class="w-4 h-4 rounded-full"
                      :class="index === 0 ? 'bg-primary' : 'bg-muted'"
                    />
                    <div
                      v-if="index < order.status_history.length - 1"
                      class="w-0.5 h-12 bg-muted"
                    />
                  </div>
                  <div class="flex-1 pb-4">
                    <div class="flex justify-between">
                      <p class="font-medium">{{ formatStatus(history.status) }}</p>
                      <p class="text-sm text-muted-foreground">
                        {{ new Date(history.created_at).toLocaleString() }}
                      </p>
                    </div>
                    <p v-if="history.note" class="text-sm text-muted-foreground mt-1">
                      {{ history.note }}
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <div class="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Order Summary</CardTitle>
            </CardHeader>
            <CardContent class="space-y-3">
              <div class="flex justify-between">
                <span class="text-muted-foreground">Subtotal</span>
                <span>${{ Number(order.total_amount).toFixed(2) }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-muted-foreground">Shipping</span>
                <span>Free</span>
              </div>
              <Separator />
              <div class="flex justify-between text-lg font-bold">
                <span>Total</span>
                <span class="text-primary">${{ Number(order.total_amount).toFixed(2) }}</span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Shipping Address</CardTitle>
            </CardHeader>
            <CardContent>
              <p class="whitespace-pre-line">{{ order.shipping_address }}</p>
            </CardContent>
          </Card>

          <Card v-if="order.status === 'pending'">
            <CardHeader>
              <CardTitle>Actions</CardTitle>
            </CardHeader>
            <CardContent>
              <Button variant="destructive" class="w-full" @click="handleCancelOrder">
                Cancel Order
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>

    <div v-else class="text-center py-12">
      <p class="text-muted-foreground">Order not found</p>
      <Button class="mt-4" @click="navigateTo('/orders')">
        Back to Orders
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Order } from '@bookstore/types'

const route = useRoute()
const { api } = useApi()
const toast = useToast()

const order = ref<Order | null>(null)
const loading = ref(true)

const fetchOrder = async () => {
  loading.value = true
  try {
    order.value = await api.getOrder(Number(route.params.id))
  } catch (error) {
    console.error('Failed to fetch order:', error)
    toast.error('Failed to load order')
  } finally {
    loading.value = false
  }
}

const handleCancelOrder = async () => {
  try {
    await api.cancelOrder(Number(route.params.id))
    toast.success('Order cancelled')
    await fetchOrder()
  } catch (error) {
    toast.error('Failed to cancel order')
  }
}

const getStatusVariant = (status: string): 'default' | 'secondary' | 'destructive' | 'outline' => {
  const variants: Record<string, 'default' | 'secondary' | 'destructive' | 'outline'> = {
    pending: 'secondary',
    paid: 'default',
    shipped: 'default',
    completed: 'default',
    cancelled: 'destructive',
  }
  return variants[status] || 'outline'
}

const formatStatus = (status: string) => {
  const formatted: Record<string, string> = {
    pending: 'Pending',
    paid: 'Paid',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    completed: 'Completed',
    cancelled: 'Cancelled',
  }
  return formatted[status] || status
}

onMounted(() => {
  fetchOrder()
})
</script>

// apps/frontend/src/app/orders/[id]/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, BookOpen, Package, Clock, CheckCircle, XCircle, Truck, CreditCard } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import { useAuthStore } from '@/stores/auth';
import { api } from '@/lib/api';
import { toast } from 'sonner';
import type { Order, OrderTracking } from '@/types';

const statusConfig = {
  pending: { label: 'Pending', icon: Clock, variant: 'secondary' as const, color: 'text-yellow-600 bg-yellow-100' },
  paid: { label: 'Paid', icon: CreditCard, variant: 'default' as const, color: 'text-blue-600 bg-blue-100' },
  shipped: { label: 'Shipped', icon: Truck, variant: 'default' as const, color: 'text-purple-600 bg-purple-100' },
  completed: { label: 'Completed', icon: CheckCircle, variant: 'default' as const, color: 'text-green-600 bg-green-100' },
  cancelled: { label: 'Cancelled', icon: XCircle, variant: 'destructive' as const, color: 'text-red-600 bg-red-100' },
};

export default function OrderDetailPage() {
  const params = useParams();
  const router = useRouter();
  const { user, isInitialized } = useAuthStore();
  const [order, setOrder] = useState<Order | null>(null);
  const [tracking, setTracking] = useState<OrderTracking | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isCancelling, setIsCancelling] = useState(false);

  const orderId = parseInt(params.id as string);

  useEffect(() => {
    if (isInitialized && !user) {
      router.push('/login');
    }
  }, [isInitialized, user, router]);

  useEffect(() => {
    async function fetchOrder() {
      if (!user) return;
      setIsLoading(true);
      try {
        const [orderData, trackingData] = await Promise.all([
          api.getOrder(orderId),
          api.getOrderTracking(orderId),
        ]);
        setOrder(orderData);
        setTracking(trackingData);
      } catch (error) {
        toast.error('Failed to load order');
        router.push('/orders');
      } finally {
        setIsLoading(false);
      }
    }
    fetchOrder();
  }, [user, orderId, router]);

  const handleCancelOrder = async () => {
    if (!order) return;
    setIsCancelling(true);
    try {
      const updatedOrder = await api.cancelOrder(order.id);
      setOrder(updatedOrder);
      const trackingData = await api.getOrderTracking(orderId);
      setTracking(trackingData);
      toast.success('Order cancelled successfully');
    } catch (error) {
      toast.error((error as Error).message);
    } finally {
      setIsCancelling(false);
    }
  };

  if (!isInitialized || !user || isLoading) {
    return (
      <div className="container py-8">
        <Skeleton className="h-6 w-32 mb-6" />
        <Skeleton className="h-10 w-64 mb-8" />
        <div className="grid lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-4">
            <Skeleton className="h-48 w-full" />
            <Skeleton className="h-32 w-full" />
          </div>
          <Skeleton className="h-64 w-full" />
        </div>
      </div>
    );
  }

  if (!order) {
    return (
      <div className="container py-8 text-center">
        <h1 className="text-2xl font-bold mb-4">Order not found</h1>
        <Link href="/orders">
          <Button>Back to Orders</Button>
        </Link>
      </div>
    );
  }

  const status = statusConfig[order.status];
  const StatusIcon = status.icon;
  const canCancel = order.status === 'pending';

  return (
    <div className="container py-8">
      <Link href="/orders" className="inline-flex items-center text-muted-foreground hover:text-foreground mb-6">
        <ArrowLeft className="h-4 w-4 mr-2" />
        Back to Orders
      </Link>

      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-3xl font-bold">Order #{order.id}</h1>
          <p className="text-muted-foreground">
            Placed on {new Date(order.created_at).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
              hour: '2-digit',
              minute: '2-digit',
            })}
          </p>
        </div>
        <Badge variant={status.variant} className="gap-1 text-base px-4 py-2">
          <StatusIcon className="h-4 w-4" />
          {status.label}
        </Badge>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-6">
          {/* Order Items */}
          <Card>
            <CardHeader>
              <CardTitle>Order Items</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
               {order.items.map((item) => (
                 <div key={item.id} className="flex gap-4">
                   {item.book_cover_image ? (
                     <div className="w-20 h-28 bg-muted rounded-md flex items-center justify-center shrink-0 overflow-hidden">
                       <img
                         src={item.book_cover_image}
                         alt={item.book_title || 'Book'}
                         className="w-full h-full object-cover"
                       />
                     </div>
                   ) : (
                     <div className="w-20 h-28 bg-muted rounded-md flex items-center justify-center shrink-0">
                       <BookOpen className="h-6 w-6 text-muted-foreground" />
                     </div>
                   )}
                   <div className="flex-1">
                     <h3 className="font-semibold">
                       {item.book_title || 'Book (no longer available)'}
                     </h3>
                     {item.book_author && <p className="text-sm text-muted-foreground">{item.book_author}</p>}
                     <p className="text-sm text-muted-foreground">Qty: {item.quantity}</p>
                   </div>
                   <div className="text-right">
                     <p className="font-bold">${item.price_at_purchase}</p>
                     <p className="text-sm text-muted-foreground">each</p>
                   </div>
                 </div>
               ))}
            </CardContent>
          </Card>

          {/* Order Timeline */}
          {tracking && tracking.status_history && tracking.status_history.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Order Timeline</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {tracking.status_history.map((event, index) => {
                    const eventStatus = statusConfig[event.status];
                    const EventIcon = eventStatus.icon;
                    const isLast = index === tracking.status_history.length - 1;
                    return (
                      <div key={event.id} className="flex gap-4">
                        <div className="flex flex-col items-center">
                          <div className={`p-2 rounded-full ${eventStatus.color}`}>
                            <EventIcon className="h-4 w-4" />
                          </div>
                          {!isLast && <div className="w-0.5 h-full bg-border mt-2" />}
                        </div>
                        <div className="pb-4">
                          <p className="font-medium">{eventStatus.label}</p>
                          {event.note && <p className="text-sm text-muted-foreground">{event.note}</p>}
                          <p className="text-xs text-muted-foreground mt-1">
                            {new Date(event.created_at).toLocaleDateString('en-US', {
                              year: 'numeric',
                              month: 'short',
                              day: 'numeric',
                              hour: '2-digit',
                              minute: '2-digit',
                            })}
                          </p>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </CardContent>
            </Card>
          )}
        </div>

        {/* Order Summary */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Order Summary</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Items ({order.items.length})</span>
                <span>${order.total_amount}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Shipping</span>
                <span className="text-green-600">Free</span>
              </div>
              <Separator />
              <div className="flex justify-between text-lg font-bold">
                <span>Total</span>
                <span>${order.total_amount}</span>
              </div>
            </CardContent>
          </Card>

          {/* Shipping Address */}
          <Card>
            <CardHeader>
              <CardTitle>Shipping Address</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="whitespace-pre-line text-sm">{order.shipping_address}</p>
            </CardContent>
          </Card>

          {/* Actions */}
          {canCancel && (
            <Card>
              <CardContent className="pt-6">
                <Button
                  variant="destructive"
                  className="w-full"
                  onClick={handleCancelOrder}
                  disabled={isCancelling}
                >
                  {isCancelling ? 'Cancelling...' : 'Cancel Order'}
                </Button>
              </CardContent>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
