// apps/admin/src/app/orders/[id]/page.tsx
"use client";

import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Button } from "@bookstore/ui";
import { Input } from "@bookstore/ui";
import { Label } from "@bookstore/ui";
import { Card, CardContent, CardHeader, CardTitle } from "@bookstore/ui";
import { Badge } from "@bookstore/ui";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@bookstore/ui";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@bookstore/ui";
import { Skeleton } from "@bookstore/ui";
import { ArrowLeft, Clock, X } from "lucide-react";
import { api } from "@/lib/api";
import type { Order as BaseOrder } from "@bookstore/types";

interface StatusHistoryEntry {
  id?: number;
  new_status?: string;
  status?: string;
  timestamp?: string;
  created_at?: string;
  note?: string | null;
}

interface Order extends Omit<BaseOrder, 'status_history'> {
  user_email?: string;
  status_history?: StatusHistoryEntry[];
}
import { toast } from "sonner";

const STATUS_STYLES: Record<string, string> = {
  pending: "bg-amber-100 text-amber-700 hover:bg-amber-100",
  paid: "bg-blue-100 text-blue-700 hover:bg-blue-100",
  shipped: "bg-violet-100 text-violet-700 hover:bg-violet-100",
  completed: "bg-emerald-100 text-emerald-700 hover:bg-emerald-100",
  cancelled: "bg-red-100 text-red-700 hover:bg-red-100",
};

const STATUS_TRANSITIONS: Record<string, string[]> = {
  pending: ["paid", "cancelled"],
  paid: ["shipped", "cancelled"],
  shipped: ["completed", "cancelled"],
  completed: [],
  cancelled: [],
};

export default function OrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const router = useRouter();
  const [order, setOrder] = useState<Order | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isUpdating, setIsUpdating] = useState(false);
  const [status, setStatus] = useState("");
  const [note, setNote] = useState("");

  useEffect(() => {
    async function loadOrder() {
      setIsLoading(true);
      try {
        const data = await api.getAdminOrder(parseInt(id)) as Order;
        setOrder(data);
        setStatus(data.status);
      } catch {
        toast.error("Failed to load order");
        router.push("/orders");
      } finally {
        setIsLoading(false);
      }
    }
    loadOrder();
  }, [id]);

  const handleStatusUpdate = async () => {
    if (!order || !status) return;

    setIsUpdating(true);
    try {
      const updated = await api.updateOrderStatus(order.id, status, note || undefined) as Order;
      setOrder(updated);
      toast.success(`Order status updated to ${status}`);
      setNote("");
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "Failed to update status");
    } finally {
      setIsUpdating(false);
    }
  };

  const handleCancelOrder = async () => {
    if (!order) return;

    setIsUpdating(true);
    try {
      const updated = await api.updateOrderStatus(order.id, "cancelled", "Cancelled by admin") as Order;
      setOrder(updated);
      setStatus("cancelled");
      toast.success("Order cancelled");
    } catch {
      toast.error("Failed to cancel order");
    } finally {
      setIsUpdating(false);
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Skeleton className="h-8 w-8" />
          <Skeleton className="h-8 w-40" />
        </div>
        <div className="grid md:grid-cols-2 gap-6">
          <Card><CardContent className="p-6 space-y-4">
            {[...Array(6)].map((_, i) => <Skeleton key={i} className="h-6 w-full" />)}
          </CardContent></Card>
          <Card><CardContent className="p-6 space-y-4">
            {[...Array(3)].map((_, i) => <Skeleton key={i} className="h-10 w-full" />)}
          </CardContent></Card>
        </div>
      </div>
    );
  }

  if (!order) {
    return (
      <div className="flex flex-col items-center justify-center py-16 text-center">
        <p className="text-muted-foreground mb-4">Order not found</p>
        <Link href="/orders">
          <Button>Back to Orders</Button>
        </Link>
      </div>
    );
  }

  const availableStatuses = STATUS_TRANSITIONS[order.status] || [];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Link href="/orders">
          <Button variant="ghost" size="icon" className="h-8 w-8">
            <ArrowLeft className="h-4 w-4" />
          </Button>
        </Link>
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-bold tracking-tight">Order #{order.id}</h1>
          <Badge variant="secondary" className={`font-normal capitalize ${STATUS_STYLES[order.status] || ""}`}>
            {order.status}
          </Badge>
        </div>
      </div>

      {/* Order Details */}
      <div className="grid md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Order Information</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {[
              { label: "User", value: order.user_email || "N/A" },
              { label: "Payment Reference", value: order.payment_reference || "N/A" },
              { label: "Shipping Address", value: order.shipping_address },
              { label: "Created", value: new Date(order.created_at).toLocaleString() },
            ].map((item) => (
              <div key={item.label}>
                <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{item.label}</p>
                <p className="mt-0.5 font-medium">{item.value}</p>
              </div>
            ))}
            <div>
              <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">Total Amount</p>
              <p className="mt-0.5 text-2xl font-bold">${parseFloat(String(order.total_amount)).toFixed(2)}</p>
            </div>
          </CardContent>
        </Card>

        {/* Status Update */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Update Status</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="status">New Status</Label>
              <Select
                value={status}
                onValueChange={setStatus}
                disabled={isUpdating}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select status" />
                </SelectTrigger>
                <SelectContent>
                  {availableStatuses.length > 0 ? (
                    availableStatuses.map((s) => (
                      <SelectItem key={s} value={s} className="capitalize">
                        {s}
                      </SelectItem>
                    ))
                  ) : (
                    <SelectItem value={order.status} disabled>
                      {order.status} (current)
                    </SelectItem>
                  )}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="note">Note (optional)</Label>
              <Input
                id="note"
                value={note}
                onChange={(e) => setNote(e.target.value)}
                placeholder="Add a note about this status change..."
                disabled={isUpdating}
              />
            </div>

            <div className="flex gap-2">
              <Button
                onClick={handleStatusUpdate}
                disabled={isUpdating || !status || status === order.status}
              >
                {isUpdating ? "Updating..." : "Update Status"}
              </Button>
              {order.status !== "cancelled" && order.status !== "completed" && (
                <Button
                  variant="destructive"
                  onClick={handleCancelOrder}
                  disabled={isUpdating}
                >
                  <X className="mr-2 h-4 w-4" />
                  Cancel Order
                </Button>
              )}
            </div>

            {order.status === "completed" && (
              <p className="text-sm text-muted-foreground">
                This order is complete and cannot be changed.
              </p>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Order Items */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Order Items</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          {order.items && order.items.length > 0 ? (
            <Table>
              <TableHeader>
                <TableRow className="hover:bg-transparent">
                  <TableHead>Book Title</TableHead>
                  <TableHead>Author</TableHead>
                  <TableHead>Quantity</TableHead>
                  <TableHead>Price</TableHead>
                  <TableHead>Subtotal</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {order.items.map((item) => (
                  <TableRow key={item.id} className="hover:bg-muted/50 transition-colors">
                    <TableCell className="font-medium">{item.book_title}</TableCell>
                    <TableCell className="text-muted-foreground">{item.book_author}</TableCell>
                    <TableCell>{item.quantity}</TableCell>
                    <TableCell>${parseFloat(String(item.price_at_purchase)).toFixed(2)}</TableCell>
                    <TableCell className="font-medium">
                      ${(parseFloat(String(item.price_at_purchase)) * item.quantity).toFixed(2)}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          ) : (
            <div className="text-center py-8 text-muted-foreground">
              No items found
            </div>
          )}
        </CardContent>
      </Card>

      {/* Status History */}
      {order.status_history && order.status_history.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Status History</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {order.status_history.map((entry, index) => (
                <div key={index} className="flex gap-4 items-start">
                  <div className="flex-shrink-0 mt-0.5">
                    <Clock className="h-4 w-4 text-muted-foreground" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <Badge variant="secondary" className={`font-normal capitalize ${STATUS_STYLES[entry.new_status || entry.status || ""] || ""}`}>
                        {entry.new_status || entry.status}
                      </Badge>
                      <span className="text-xs text-muted-foreground">
                        {new Date(entry.timestamp || entry.created_at || "").toLocaleString()}
                      </span>
                    </div>
                    {entry.note && (
                      <p className="text-sm mt-1 text-muted-foreground">
                        {entry.note}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

// apps/frontend-nuxt/src/pages/orders/[id].vue
<template>
  <div class="container py-8">
    <div v-if="loading" class="max-w-4xl mx-auto space-y-8">
      <div class="h-32 animate-pulse rounded-xl bg-muted" />
      <div class="grid md:grid-cols-3 gap-8">
        <div class="md:col-span-2 space-y-4">
          <div v-for="i in 3" :key="`skeleton-${i}`" class="h-40 animate-pulse rounded-xl bg-muted" />
        </div>
        <div class="space-y-4">
          <div class="h-60 animate-pulse rounded-xl bg-muted" />
        </div>
      </div>
    </div>

    <div v-else-if="order" class="max-w-4xl mx-auto">
      <Button variant="ghost" class="mb-6" @click="navigateTo('/orders')">
        ← Back to Orders
      </Button>

      <Card class="mb-8">
        <CardContent class="p-6">
          <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
              <h1 class="text-2xl font-bold mb-1">Order #{{ order.id }}</h1>
              <p class="text-muted-foreground">Placed on {{ new Date(order.created_at).toLocaleDateString() }}</p>
            </div>
            <Badge :variant="getStatusVariant(order.status)" class="text-sm px-4 py-2">
              {{ formatStatus(order.status) }}
            </Badge>
          </div>
        </CardContent>
      </Card>

      <div class="grid md:grid-cols-3 gap-8">
        <div class="md:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Order Items</CardTitle>
            </CardHeader>
            <CardContent>
              <div class="space-y-4">
                <div v-for="item in order.items" :key="item.id" class="flex gap-4 py-4 border-b last:border-0">
                  <img
                    :src="item.book_cover_image || 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=100&h=150&fit=crop'"
                    :alt="item.book_title || ''"
                    class="w-20 h-28 object-cover rounded-lg"
                  />
                  <div class="flex-1">
                    <p class="font-semibold">{{ item.book_title }}</p>
                    <p class="text-sm text-muted-foreground">{{ item.book_author }}</p>
                    <p class="text-sm text-muted-foreground mt-1">Qty: {{ item.quantity }}</p>
                  </div>
                  <div class="text-right">
                    <p class="font-bold">${{ (Number(item.price_at_purchase) * item.quantity).toFixed(2) }}</p>
                    <p class="text-sm text-muted-foreground">${{ item.price_at_purchase }} each</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card v-if="order.status_history && order.status_history.length > 0">
            <CardHeader>
              <CardTitle>Order Status History</CardTitle>
            </CardHeader>
            <CardContent>
              <div class="space-y-4">
                <div
                  v-for="(history, index) in order.status_history"
                  :key="history.id"
                  class="flex gap-4"
                >
                  <div class="flex flex-col items-center">
                    <div
                      class="w-4 h-4 rounded-full"
                      :class="index === 0 ? 'bg-primary' : 'bg-muted'"
                    />
                    <div
                      v-if="index < order.status_history.length - 1"
                      class="w-0.5 h-12 bg-muted"
                    />
                  </div>
                  <div class="flex-1 pb-4">
                    <div class="flex justify-between">
                      <p class="font-medium">{{ formatStatus(history.status) }}</p>
                      <p class="text-sm text-muted-foreground">
                        {{ new Date(history.created_at).toLocaleString() }}
                      </p>
                    </div>
                    <p v-if="history.note" class="text-sm text-muted-foreground mt-1">
                      {{ history.note }}
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <div class="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Order Summary</CardTitle>
            </CardHeader>
            <CardContent class="space-y-3">
              <div class="flex justify-between">
                <span class="text-muted-foreground">Subtotal</span>
                <span>${{ Number(order.total_amount).toFixed(2) }}</span>
              </div>
              <div class="flex justify-between">
                <span class="text-muted-foreground">Shipping</span>
                <span>Free</span>
              </div>
              <Separator />
              <div class="flex justify-between text-lg font-bold">
                <span>Total</span>
                <span class="text-primary">${{ Number(order.total_amount).toFixed(2) }}</span>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Shipping Address</CardTitle>
            </CardHeader>
            <CardContent>
              <p class="whitespace-pre-line">{{ order.shipping_address }}</p>
            </CardContent>
          </Card>

          <Card v-if="order.status === 'pending'">
            <CardHeader>
              <CardTitle>Actions</CardTitle>
            </CardHeader>
            <CardContent>
              <Button variant="destructive" class="w-full" @click="handleCancelOrder">
                Cancel Order
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>

    <div v-else class="text-center py-12">
      <p class="text-muted-foreground">Order not found</p>
      <Button class="mt-4" @click="navigateTo('/orders')">
        Back to Orders
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Order } from '@bookstore/types'

const route = useRoute()
const { api } = useApi()
const toast = useToast()

const order = ref<Order | null>(null)
const loading = ref(true)

const fetchOrder = async () => {
  loading.value = true
  try {
    order.value = await api.getOrder(Number(route.params.id))
  } catch (error) {
    console.error('Failed to fetch order:', error)
    toast.error('Failed to load order')
  } finally {
    loading.value = false
  }
}

const handleCancelOrder = async () => {
  try {
    await api.cancelOrder(Number(route.params.id))
    toast.success('Order cancelled')
    await fetchOrder()
  } catch (error) {
    toast.error('Failed to cancel order')
  }
}

const getStatusVariant = (status: string): 'default' | 'secondary' | 'destructive' | 'outline' => {
  const variants: Record<string, 'default' | 'secondary' | 'destructive' | 'outline'> = {
    pending: 'secondary',
    paid: 'default',
    shipped: 'default',
    completed: 'default',
    cancelled: 'destructive',
  }
  return variants[status] || 'outline'
}

const formatStatus = (status: string) => {
  const formatted: Record<string, string> = {
    pending: 'Pending',
    paid: 'Paid',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    completed: 'Completed',
    cancelled: 'Cancelled',
  }
  return formatted[status] || status
}

onMounted(() => {
  fetchOrder()
})
</script>
