// apps/frontend-nuxt/src/pages/orders/index.vue
<template>
  <div class="container py-8">
    <h1 class="text-3xl font-bold mb-8">My Orders</h1>

    <div v-if="loading" class="text-center py-12">
      <p>Loading orders...</p>
    </div>

    <div v-else-if="orders.length === 0" class="text-center py-12">
      <p class="text-muted-foreground mb-4">You haven't placed any orders yet</p>
      <Button @click="navigateTo('/books')">
        Start Shopping
      </Button>
    </div>

    <div v-else class="space-y-4">
      <Card v-for="order in orders" :key="order.id">
        <CardHeader>
          <div class="flex justify-between items-start">
            <div>
              <CardTitle>Order #{{ order.id }}</CardTitle>
              <CardDescription>
                {{ new Date(order.created_at).toLocaleDateString() }}
              </CardDescription>
            </div>
            <Badge :variant="getStatusVariant(order.status)">
              {{ order.status }}
            </Badge>
          </div>
        </CardHeader>
        <CardContent>
          <div class="space-y-2">
            <p class="text-sm"><span class="text-muted-foreground">Items:</span> {{ order.total_items }}</p>
            <p class="text-sm"><span class="text-muted-foreground">Total:</span> ${{ Number(order.total_amount).toFixed(2) }}</p>
            <p class="text-sm"><span class="text-muted-foreground">Shipping:</span> {{ order.shipping_address }}</p>
          </div>
          <Button variant="outline" size="sm" class="mt-4" @click="viewOrder(order.id)">
            View Details
          </Button>
        </CardContent>
      </Card>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { OrderListItem, PaginatedResponse } from '@bookstore/types'

const { api } = useApi()
const toast = useToast()

const loading = ref(true)
const orders = ref<OrderListItem[]>([])

const fetchOrders = async () => {
  loading.value = true
  try {
    const response: PaginatedResponse<OrderListItem> = await api.getOrders({
      page: 1,
      size: 20,
    })
    orders.value = response.items
  } catch (error) {
    console.error('Failed to fetch orders:', error)
    toast.error('Failed to load orders')
  } finally {
    loading.value = false
  }
}

const getStatusVariant = (status: string) => {
  switch (status) {
    case 'pending':
      return 'default'
    case 'processing':
      return 'secondary'
    case 'shipped':
      return 'default'
    case 'delivered':
      return 'default'
    case 'cancelled':
      return 'destructive'
    default:
      return 'default'
  }
}

const viewOrder = (orderId: number) => {
  navigateTo(`/orders/${orderId}`)
}

onMounted(() => {
  fetchOrders()
})
</script>

// apps/frontend/src/app/admin/orders/page.tsx
'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Package, Clock, CheckCircle, XCircle, Truck, CreditCard, Eye } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { api } from '@/lib/api';
import { toast } from 'sonner';
import type { OrderListItem, PaginatedResponse, OrderStatus } from '@/types';

const statusConfig: Record<OrderStatus, { label: string; icon: React.ElementType; variant: 'default' | 'secondary' | 'destructive' }> = {
  pending: { label: 'Pending', icon: Clock, variant: 'secondary' },
  paid: { label: 'Paid', icon: CreditCard, variant: 'default' },
  shipped: { label: 'Shipped', icon: Truck, variant: 'default' },
  completed: { label: 'Completed', icon: CheckCircle, variant: 'default' },
  cancelled: { label: 'Cancelled', icon: XCircle, variant: 'destructive' },
};

export default function AdminOrdersPage() {
  const [orders, setOrders] = useState<PaginatedResponse<OrderListItem> | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [statusFilter, setStatusFilter] = useState<string>('all');

  useEffect(() => {
    async function fetchOrders() {
      setIsLoading(true);
      try {
        const params: { page: number; size: number; status?: string } = { page, size: 10 };
        if (statusFilter !== 'all') {
          params.status = statusFilter;
        }
        const data = await api.getAdminOrders(params);
        setOrders(data);
      } catch (error) {
        toast.error('Failed to load orders');
      } finally {
        setIsLoading(false);
      }
    }
    fetchOrders();
  }, [page, statusFilter]);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold">Orders</h2>
        <Select value={statusFilter} onValueChange={(value) => { setStatusFilter(value); setPage(1); }}>
          <SelectTrigger className="w-48">
            <SelectValue placeholder="Filter by status" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Statuses</SelectItem>
            <SelectItem value="pending">Pending</SelectItem>
            <SelectItem value="paid">Paid</SelectItem>
            <SelectItem value="shipped">Shipped</SelectItem>
            <SelectItem value="completed">Completed</SelectItem>
            <SelectItem value="cancelled">Cancelled</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {isLoading ? (
        <div className="space-y-4">
          {[1, 2, 3, 4, 5].map((i) => (
            <Skeleton key={i} className="h-20 w-full" />
          ))}
        </div>
      ) : !orders || orders.items.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <Package className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
            <p className="text-muted-foreground">No orders found</p>
          </CardContent>
        </Card>
      ) : (
        <>
          <Card>
            <CardContent className="p-0">
              <table className="w-full">
                <thead>
                  <tr className="border-b">
                    <th className="text-left p-4 font-medium">Order ID</th>
                    <th className="text-left p-4 font-medium">Date</th>
                    <th className="text-left p-4 font-medium">Items</th>
                    <th className="text-left p-4 font-medium">Total</th>
                    <th className="text-left p-4 font-medium">Status</th>
                    <th className="text-right p-4 font-medium">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {orders.items.map((order) => {
                    const status = statusConfig[order.status];
                    const StatusIcon = status.icon;
                    return (
                      <tr key={order.id} className="border-b last:border-0 hover:bg-muted/50">
                        <td className="p-4 font-medium">#{order.id}</td>
                        <td className="p-4 text-muted-foreground">
                          {new Date(order.created_at).toLocaleDateString()}
                        </td>
                        <td className="p-4">{order.item_count}</td>
                        <td className="p-4 font-semibold">${order.total_amount}</td>
                        <td className="p-4">
                          <Badge variant={status.variant} className="gap-1">
                            <StatusIcon className="h-3 w-3" />
                            {status.label}
                          </Badge>
                        </td>
                        <td className="p-4 text-right">
                          <Link href={`/admin/orders/${order.id}`}>
                            <Button variant="ghost" size="sm">
                              <Eye className="h-4 w-4 mr-1" />
                              View
                            </Button>
                          </Link>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </CardContent>
          </Card>

          {/* Pagination */}
          {orders.pages > 1 && (
            <div className="flex justify-center gap-2">
              <Button
                variant="outline"
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                disabled={page === 1}
              >
                Previous
              </Button>
              <span className="flex items-center px-4 text-sm text-muted-foreground">
                Page {page} of {orders.pages}
              </span>
              <Button
                variant="outline"
                onClick={() => setPage((p) => Math.min(orders.pages, p + 1))}
                disabled={page === orders.pages}
              >
                Next
              </Button>
            </div>
          )}
        </>
      )}
    </div>
  );
}
