// apps/frontend/src/components/ui/scroll-area.tsx
"use client"

import * as React from "react"
import * as ScrollAreaPrimitive from "@radix-ui/react-scroll-area"

import { cn } from "@bookstore/lib"

function ScrollArea({
  className,
  children,
  ...props
}: React.ComponentProps<typeof ScrollAreaPrimitive.Root>) {
  return (
    <ScrollAreaPrimitive.Root
      data-slot="scroll-area"
      className={cn("relative", className)}
      {...props}
    >
      <ScrollAreaPrimitive.Viewport
        data-slot="scroll-area-viewport"
        className="focus-visible:ring-ring/50 size-full rounded-[inherit] transition-[color,box-shadow] outline-none focus-visible:ring-[3px] focus-visible:outline-1"
      >
        {children}
      </ScrollAreaPrimitive.Viewport>
      <ScrollBar />
      <ScrollAreaPrimitive.Corner />
    </ScrollAreaPrimitive.Root>
  )
}

function ScrollBar({
  className,
  orientation = "vertical",
  ...props
}: React.ComponentProps<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>) {
  return (
    <ScrollAreaPrimitive.ScrollAreaScrollbar
      data-slot="scroll-area-scrollbar"
      orientation={orientation}
      className={cn(
        "flex touch-none p-px transition-colors select-none",
        orientation === "vertical" &&
          "h-full w-2.5 border-l border-l-transparent",
        orientation === "horizontal" &&
          "h-2.5 flex-col border-t border-t-transparent",
        className
      )}
      {...props}
    >
      <ScrollAreaPrimitive.ScrollAreaThumb
        data-slot="scroll-area-thumb"
        className="bg-border relative flex-1 rounded-full"
      />
    </ScrollAreaPrimitive.ScrollAreaScrollbar>
  )
}

export { ScrollArea, ScrollBar }

// apps/frontend-nuxt/src/components/ui/scroll-area/ScrollArea.vue
<script setup lang="ts">
import { ScrollAreaRoot, ScrollAreaScrollbar, ScrollAreaThumb } from 'radix-vue'
import type { HTMLAttributes, computed } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{ class?: HTMLAttributes['class'] }>()
</script>

<template>
  <ScrollAreaRoot
    :class="cn('relative overflow-hidden', props.class)"
  >
    <ScrollAreaScrollbar
      orientation="horizontal"
      class="flex h-2 w-full touch-none select-none border-t border-transparent p-[1px] transition-colors hover:border-border data-[orientation=vertical]:h-full data-[orientation=vertical]:w-2 data-[orientation=vertical]:flex-col data-[orientation=vertical]:border-l data-[orientation=vertical]:border-t-0"
    >
      <ScrollAreaThumb
        class="relative flex-1 rounded-full bg-border hover:bg-muted-foreground/50"
      />
    </ScrollAreaScrollbar>
    <ScrollAreaScrollbar
      orientation="vertical"
      class="flex h-2 w-full touch-none select-none border-t border-transparent p-[1px] transition-colors hover:border-border data-[orientation=vertical]:h-full data-[orientation=vertical]:w-2 data-[orientation=vertical]:flex-col data-[orientation=vertical]:border-l data-[orientation=vertical]:border-t-0"
    >
      <ScrollAreaThumb
        class="relative flex-1 rounded-full bg-border hover:bg-muted-foreground/50"
      />
    </ScrollAreaScrollbar>
    <slot />
  </ScrollAreaRoot>
</template>
